[package]
name = "QueueType"
version = "0.1.0"
edition = "2021"
description = "Implementation of queue type for better privacy managment"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
